name: Publish package
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
    #   GITHUB_ACTOR: ${{secrets.ORG_GITHUB_ACTOR}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - uses: actions/setup-java@v2
        with:
          distribution: adopt-openj9
          java-version: '16'

      - uses: s4u/maven-settings-action@v2.4.1
        with:
          servers: |
            [{"id": "github-kepler",
              "username": "GITHUB",
              "password": "${{secrets.GITHUB_TOKEN}}"}]

      - uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.3.967

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Semantic Release
        run: npx semantic-release
