name: Publish package
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ORG_GITHUB_ACTOR: ${{ secrets.ORG_GITHUB_ACTOR }}
      ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'


      - uses: s4u/maven-settings-action@v2.4.1
        with:
          servers: |
            [{"id": "github-kepler",
              "username": "${{secrets.ORG_GITHUB_ACTOR}}",
              "password": "${{secrets.ORG_GITHUB_TOKEN}}"},
             {"id": "github-kepler-releases",
              "username": "${{secrets.ORG_GITHUB_ACTOR}}",
              "password": "${{secrets.ORG_GITHUB_TOKEN}}"}]

      - uses: extractions/setup-just@v1

      - uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: latest

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Test clojure
        run: clojure -X:test

      - name: Test cljs
        run: clojure -M:dev:shadow-cljs release test

      - name: Semantic Release
        run: npx semantic-release
